### ISSUE TITLE
Consider a way to mark a property as optional

### ISSUE THREAD

**Issue by civitz** [civitz/viper#4]

**Comment by civitz** [comment]
A default value mechanism may as well be added to those optional properties.

The value may either be written on the enum, or in the qualifier annotation.

**Comment by filippobuletto** [comment]
I'd prefer it written on the enum so it's still centralized and not distributed everywhere in the code. Note that the default value must be validated anyway in the same way the optional value would have been validated if present

**Comment by civitz** [comment]
The solution to this has been discussed in https://github.com/civitz/viper/issues/33#issuecomment-301583973

**Comment by civitz** [comment]
Closed in #34
